// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "chat.proto" (package "Services", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Chat } from "./chat";
import type { Empty } from "./google/protobuf/empty";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ChatMessage } from "./chat";
import type { User } from "./chat";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service Services.Chat
 */
export interface IChatClient {
    /**
     * @generated from protobuf rpc: Join(Services.User) returns (stream Services.ChatMessage);
     */
    join(input: User, options?: RpcOptions): ServerStreamingCall<User, ChatMessage>;
    /**
     * @generated from protobuf rpc: SendMessage(Services.ChatMessage) returns (google.protobuf.Empty);
     */
    sendMessage(input: ChatMessage, options?: RpcOptions): UnaryCall<ChatMessage, Empty>;
}
/**
 * @generated from protobuf service Services.Chat
 */
export class ChatClient implements IChatClient, ServiceInfo {
    typeName = Chat.typeName;
    methods = Chat.methods;
    options = Chat.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Join(Services.User) returns (stream Services.ChatMessage);
     */
    join(input: User, options?: RpcOptions): ServerStreamingCall<User, ChatMessage> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<User, ChatMessage>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SendMessage(Services.ChatMessage) returns (google.protobuf.Empty);
     */
    sendMessage(input: ChatMessage, options?: RpcOptions): UnaryCall<ChatMessage, Empty> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChatMessage, Empty>("unary", this._transport, method, opt, input);
    }
}
